### PR TITLE
mbed-trace update

### PR DESCRIPTION
**Pull request by teetak01**
@yogpan01 @anttiylitokola 

Updating the example to mbed-trace

### CODE REVIEW

**Comment by yogpan01** [comment]
There is a compilation error observed in CI, please check @teetak01

**Comment by teetak01** [comment]
Yep, it still links to current mbed client with old tracelibs. This would also require local linking of mbed-client, mbed-client-linux and mbed-client-mbedtls to compile. mbed-trace will be imported from mbed-client after those components have been merged.

**Comment by yogpan01** [comment]
ok,got it . This PR needs to be merged after mbed-client PR is merged.

**Comment by teetak01** [comment]
rebuild

**Pull request merged**
